[project]
name = "markdown-semantic-search"
version = "1.3.0"
description = "Markdown Semantic Search CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.3",
    "requests>=2.32.5",
]

[project.scripts]
md-search = "main:main"
